version: '3.4'

x-common-env-vars:
  - &bot-hostname mnb-bot-live
  - &admin-panel-hostname mnb-adminpanel-live
  - &postgres-db-hostname mnb-postgres-live
  - &postgres-backup-hostname mnb-postgres-backup-live
  - &redis-hostname mnb-redis-live
  - &admin-panel-port 8111
  - &admin-panel-cmd poetry run uvicorn ballsdex.core.admin:_app --host 0.0.0.0 --port 8111
  - &postgres-db POSTGRES_DB=ballsdex
  - &postgres-user POSTGRES_USER=ballsdex
  - &postgres-url "BALLSDEXBOT_DB_URL=postgres://ballsdex:${POSTGRES_PASSWORD}@mnb-postgres-live:5432/ballsdex"
  - &redis-url "BALLSDEXBOT_REDIS_URL=redis://mnb-redis-live"
  - &postgres-host POSTGRES_HOST=mnb-postgres-live
  - &traefik-cfg
      - "traefik.enable=true"
      - "traefik.http.routers.mbda.rule=Host(`balls.pantonianrepublic.com`)"
      - "traefik.http.routers.mbda.entrypoints=websecure"
      - "traefik.http.routers.mbda.tls.certresolver=mpede"
      - "traefik.http.routers.mbda.service=mbda"
      - "traefik.http.services.mbda.loadbalancer.server.port=8111"


services:

  bot:
    restart: "no"
    image: ballsdex
    hostname: *bot-hostname
    build: .
    environment:
      - *postgres-url
    depends_on:
      - postgres-db
    volumes:
      - type: bind
        source: ./
        target: /code
    tty: true
    command: poetry run python3 -m ballsdex --dev

  admin-panel:
    image: ballsdex
    hostname: *admin-panel-hostname
    expose:
      - *admin-panel-port
    environment:
      - *postgres-url
      - *redis-url
    depends_on:
      - postgres-db
      - redis-cache
    volumes:
      - type: bind
        source: ./
        target: /code
    tty: true
    command: *admin-panel-cmd
    labels: *traefik-cfg


  postgres-db:
    image: postgres
    restart: always
    hostname: *postgres-db-hostname
    environment:
      - *postgres-db
      - *postgres-user
      - POSTGRES_PASSWORD
    volumes: 
      - database-data:/var/lib/postgresql/data

  postgres-backup:
    image: prodrigestivill/postgres-backup-local
    restart: always
    user: postgres:postgres
    hostname: *postgres-backup-hostname
    volumes:
      - /var/opt/pgbackups:/backups
    depends_on:
      - postgres-db
    environment:
      - *postgres-db
      - *postgres-user
      - POSTGRES_PASSWORD
      - *postgres-host
      - SCHEDULE=@daily
      - BACKUP_KEEP_DAYS=7
      - BACKUP_KEEP_WEEKS=4
      - BACKUP_KEEP_MONTHS=6
      - HEALTHCHECK_PORT=3928

  redis-cache:
    image: redis:latest
    restart: always
    hostname: *redis-hostname
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    command: redis-server --save 20 1 --loglevel warning
    volumes: 
      - cache-data:/data


volumes:
  database-data:
  cache-data:

networks:
  default: 
    name: traefik
    external: true
