name: Deploy Dev Bot 

on:
  workflow_dispatch:

jobs:
  deploy_dev_bot:
    runs-on: ubuntu-latest
    steps:
    - name: multiple commands
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.MNBD_HOST }}
        username: ${{ secrets.MNBD_USERNAME }}
        password: ${{ secrets.MNBD_PASSWORD }}
        script: |
          cd /opt/mnballsdex_dev
          sudo docker-compose down
          sleep 3
          sudo git checkout dev
          sudo git fetch 
          sudo git pull 
          sudo docker-compose up -d
          sleep 7
          sudo docker-compose logs -t postgres-db
          sudo docker-compose logs -t bot
          sudo docker-compose logs -t admin-panel
          sleep 3
          sudo docker-compose ps
