name: Restart bot to make new balls live

on:
  workflow_dispatch:

jobs:
  restart_bot:
    runs-on: ubuntu-latest
    steps:
    - name: multiple commands
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.MNBD_HOST }}
        username: ${{ secrets.MNBD_USERNAME }}
        password: ${{ secrets.MNBD_PASSWORD }}
        script: |
          cd /opt/mnballsdex_live
          sudo docker-compose restart bot
